version: '3'

networks:
  nginx_net:
    external:
      name: nginx_net


services:
  web:
    container_name: "wordle_web"
    image: fumaz/ubuntu-20.04
    build: .
    restart: unless-stopped
    networks:
      - nginx_net